apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: {{ .Values.prometheus.scrape }}
    # prometheus.io/port: {{ .Values.prometheus.port }}
    prometheus.io/path: {{ .Values.prometheus.path }}
  name: {{ include "cross_chart.fullname" . }}
  labels:
    {{- include "cross_chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - name: prometheus
      port: 80
      targetPort: prometheus
  selector:
    {{- include "cross_chart.selectorLabels" . | nindent 4 }}
